openapi: "3.0.1"
info:
  title: "Poller Tasks Http API"
  version: "2021-04-07"
tags:
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  /jobs/{jobId}:
    get:
      responses:
        default:
          description: "Default response for GET /jobs/{jobId}"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [PollerHttpApiRole, Arn]
        uri: 
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JobsGetJobSummaryFunction.Arn}/invocations"
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        connectionType: "INTERNET"
  /jobs:
    post:
      responses:
        default:
          description: "Default response for POST /jobs"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"
        credentials:
           Fn::GetAtt: [PollerHttpApiRole, Arn]
        requestParameters:
          EventBusName: 
            Ref: PollerEventBus
          Detail: "$request.body"
          DetailType: "api.event"
          Source: "source.events"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "GET"
  - "OPTIONS"
  - "POST"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-amz-date"
  - "x-amzm-header"
  - "x-api-key"
  - "x-apigateway-header"
  maxAge: 60
  allowCredentials: false
x-amazon-apigateway-importexport-version: "1.0"